'use strict';
const assert = require('node:assert/strict');
const { assessAudit } = require('./client_audit.cjs');
const zero = { auditReportVersion: 2, vulnerabilities: {}, metadata: { vulnerabilities: { total: 0 } } };
assert.equal(assessAudit(zero).findings, 0);
const known = structuredClone(zero);
known.metadata.vulnerabilities.total = 1;
known.vulnerabilities.braces = { name: 'braces', nodes: ['node_modules/braces'], via: [{ url: 'https://github.com/advisories/GHSA-vfj7-8cjw-p6xm' }] };
assert.equal(assessAudit(known).findings, 1, 'Known findings remain reported, not erased');
const unknown = structuredClone(known);
unknown.vulnerabilities.braces.via[0].url = 'https://github.com/advisories/GHSA-new1-new2-new3';
assert.throws(() => assessAudit(unknown), /Unreviewed advisory/);
const newPath = structuredClone(known);
newPath.vulnerabilities.other = newPath.vulnerabilities.braces;
delete newPath.vulnerabilities.braces;
assert.throws(() => assessAudit(newPath), /Unreviewed dependency path/);
assert.throws(() => assessAudit({ error: { code: 'network' } }), /unavailable/);
assert.throws(() => assessAudit({ ...zero, metadata: { vulnerabilities: { total: 1 } } }), /inconsistent/);
const unresolved = structuredClone(known);
unresolved.vulnerabilities.braces.via = ['not-in-report'];
assert.throws(() => assessAudit(unresolved), /unresolved advisory chain/);
const nested = structuredClone(known);
nested.vulnerabilities.braces.nodes.push('node_modules/unreviewed-capture-plugin/node_modules/braces');
assert.throws(() => assessAudit(nested), /Unreviewed installation path/);
const missingNodes = structuredClone(known);
delete missingNodes.vulnerabilities.braces.nodes;
assert.throws(() => assessAudit(missingNodes), /Unreviewed installation path/);
const cycle = structuredClone(known);
cycle.metadata.vulnerabilities.total = 3;
cycle.vulnerabilities.chokidar = { name: 'chokidar', nodes: ['node_modules/chokidar'], via: ['micromatch'] };
cycle.vulnerabilities.micromatch = { name: 'micromatch', nodes: ['node_modules/micromatch'], via: ['chokidar'] };
assert.throws(() => assessAudit(cycle), /without approved advisory evidence/);
cycle.vulnerabilities.micromatch.via.push('braces');
assert.equal(assessAudit(cycle).findings, 3, 'A genuine dependency cycle with reviewed leaf evidence is valid');
console.log('Dependency policy checks: 11 passed (new advisories, nested paths, isolated cycles and unavailable audits fail closed)');
